import esbuild from "esbuild";
import fs from "fs";
import process from "process";
import module from "module";

const builtins = module.builtinModules;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/`;

const prod = process.argv[2] === "production";

/**
 * Production build:
 *   npm run build
 *   -> writes main.js and styles.css to project root
 *
 * Development build:
 *   npm run dev
 *   -> writes to OBSIDIAN_PLUGIN_DIR if set,
 *      otherwise writes to your local development vault path
 */
const pluginDir = prod
    ? "."
    : process.env.OBSIDIAN_PLUGIN_DIR ||
      "C:/Users/ShifuMaster/Documents/Obsidian Vault/.obsidian/plugins/obsidian-manga-reader";

fs.mkdirSync(pluginDir, { recursive: true });

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: {
        main: "src/main.ts",
        styles: "src/styles/main.css",
    },
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outdir: pluginDir,
    define: {
        "process.env.NODE_ENV": prod ? '"production"' : '"development"',
    },
});

fs.copyFileSync("manifest.json", `${pluginDir}/manifest.json`);

if (prod) {
    await context.rebuild();
    await context.dispose();
    process.exit(0);
} else {
    await context.watch();
    console.log(`⚡ [Esbuild] Watching files. Output: ${pluginDir}`);
}