import esbuild from "esbuild";
import fs from "fs";
import process from "process";
import module from "module"; // Используем встроенный модуль Node

const builtins = module.builtinModules; // Получаем список встроенных модулей напрямую

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/`;

const prod = (process.argv[2] === "production");
// Внешняя дирректория, куда выгружаю готовые файлы для плагина
const pluginDir = "C:/Users/ShifuMaster/Documents/Obsidian Vault/.obsidian/plugins/obsidian-manga-reader";
fs.mkdirSync(pluginDir, { recursive: true });

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: {
        main: "src/main.ts",
        styles: "src/styles/main.css"   // Стили собираем из единой точки сбора
    },
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins],
    format: "cjs", // Obsidian ожидает CommonJS на выходе
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outdir: pluginDir,
    // outfile: `${pluginDir}/main.js`,  // Заменяем на outdir - иначе импорты не будут срабатывать
    define: {
        'process.env.NODE_ENV': prod ? '"production"' : '"development"'
    }
});

// Больше не нужно копировать отдельно styles.css в папку конечную - есть в entryPoints и outdir
fs.copyFileSync("manifest.json", `${pluginDir}/manifest.json`);

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch(); // Включаем режим слежения за файлами
    console.log("⚡ [Esbuild] Режим отслеживания включен. Жду изменений...");
}